  services:
    - type: web
      name: vaultlinks-backend
      env: python
      rootDir: backend
      buildCommand: pip install -r requirements.txt
      startCommand: python server.py
      plan: free